CREATE TRIGGER PRODUCT_LOG_DELETE ON Product
AFTER UPDATE
AS
BEGIN

DECLARE @LOG_HOSTNAME AS VARCHAR(250) =HOST_NAME()
DECLARE @LOG_DATE AS DATETIME
set @LOG_DATE=GETDATE()
DECLARE @LOG_PROGRAM AS VARCHAR(250)=PROGRAM_NAME()
DECLARE @LOG_USERNAME AS VARCHAR(250)=SUSER_NAME()
DECLARE @LOG_ACTIONTYPE AS VARCHAR(10) ='DELETE'



INSERT INTO VTYSIdentity.DBO.Product
([Id], [Name], [Description], [Image], [Price], [Stock], [IsHome], [IsApproved], [CategoryId], [LOG_HOSTNAME], [LOG_DATE], [LOG_PROGRAM], [LOG_USERNAME], [LOG_ACTIONTYPE])

SELECT
[Id], [Name], [Description], [Image], [Price], [Stock], [IsHome], [IsApproved], [CategoryId], @LOG_HOSTNAME, @LOG_DATE, @LOG_PROGRAM, @LOG_USERNAME, @LOG_ACTIONTYPE
FROM deleted



END
