//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYSProje.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment
    {
        [Required]
        [DisplayName("Tamir Numarasý")]
        public int Id { get; set; }

        [Required]
        [DisplayName("Araç Modeli")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Ýletiþime Geçen Kiþi")]
        public string Surname { get; set; }

        [Required]
        [DisplayName("Ýletiþim Metni")]
        public string Description { get; set; }

        [Required]
        [DisplayName("Seri Numarasý")]
        public Nullable<int> ProductId { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
