//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYSProje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderLİne = new HashSet<OrderLİne>();
        }
    
        public int Id { get; set; }
        public string OrderNumber { get; set; }
        public double Total { get; set; }
        public string UserName { get; set; }
        public Nullable<int> OrderState { get; set; }
        public string AdresBasligi { get; set; }
        public string Adres { get; set; }
        public Nullable<int> CıtyId { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual City City { get; set; }
        public virtual Country Country { get; set; }
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLİne> OrderLİne { get; set; }
    }
}
