//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTYSProje.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Comment = new HashSet<Comment>();
            this.OrderLİne = new HashSet<OrderLİne>();
        }

        [Required]
        [DisplayName("Müşteri Numarası")]
        public int Id { get; set; }

        [Required]
        [DisplayName("Müşteri Adı")]
        public string Name { get; set; }

        [Required]
        [DisplayName("Tamir Açıklama")]
        public string Description { get; set; }

        [Required]
        [DisplayName("Araç Resmi")]
        public string Image { get; set; }

        [Required]
        [DisplayName("Tamir Ücreti")]
        public double Price { get; set; }

        [Required]
        [DisplayName("Araç Sorun Sayısı")]
        public int Stock { get; set; }

        [Required]
        [DisplayName("Anaysafa Gösterim")]
        public int IsHome { get; set; }

        [Required]
        [DisplayName("Tamir Durumu")]
        public int IsApproved { get; set; }

        [Required]
        [DisplayName("Seri Numarası")]
        public int CategoryId { get; set; }

        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLİne> OrderLİne { get; set; }
    }
}
