CREATE PROCEDURE SP_ADDCATEGORY
@NAME AS NVARCHAR(100),
@DESCRÝPTÝON AS NVARCHAR(100),
@BRANDID AS INT,
@CATEGORY1ID AS INT
AS
INSERT INTO Category 
( [Name], [Description], [BrandId], [Category1Id])
VALUES
(@NAME,@DESCRÝPTÝON,@BRANDID,@CATEGORY1ID)


