create TRIGGER CATEGORY_LOG_UPDATE ON Category
AFTER UPDATE
AS
BEGIN

DECLARE @LOG_HOSTNAME AS VARCHAR(250) =HOST_NAME()
DECLARE @LOG_DATE AS DATETIME
set @LOG_DATE=GETDATE()
DECLARE @LOG_PROGRAM AS VARCHAR(250)=PROGRAM_NAME()
DECLARE @LOG_USERNAME AS VARCHAR(250)=SUSER_NAME()
DECLARE @LOG_ACTIONTYPE AS VARCHAR(10) ='UPDATE'



INSERT INTO VTYSIdentity.DBO.Category
([Id], [Name], [Description], [BrandId], [Category1Id], [LOG_HOSTNAME], [LOG_DATE], [LOG_PROGRAM], [LOG_USERNAME], [LOG_ACTIONTYPE])

SELECT
[Id], [Name], [Description], [BrandId], [Category1Id], @LOG_HOSTNAME, @LOG_DATE, @LOG_PROGRAM, @LOG_USERNAME, @LOG_ACTIONTYPE
FROM deleted



END
