CREATE PROCEDURE SP_UPDATEPRODUCT
@NAME AS NVARCHAR(100),
@DESCRÝPTÝON AS NVARCHAR(100),
@IMAGE AS NVARCHAR(50),
@PRICE AS INT,
@STOCK AS INT,
@ISHOME AS INT,
@ISAPPROVED AS INT,
@CATEGORYID AS INT,
@FILTRE AS INT
AS
UPDATE Product 
SET [Name]=@NAME, [Description]=@DESCRÝPTÝON, [Image]=@IMAGE, [Price]=@PRICE, [Stock]=@STOCK, [IsHome]=@ISHOME, [IsApproved]=@ISAPPROVED, [CategoryId]=@CATEGORYID
WHERE Id=@FILTRE